#!/bin/bash
LBlue='\033[1;34m'
Green='\033[0;32m'
Bcolor='\033[0m'
printf "\n${LBlue}      -- BETA -- ${Bcolor}\n\n"
printf "\n${LBlue} INSTALLING GRO2LAM { BETA }${Bcolor}\n\n"

wget https://github.com/hernanchavezthielemann/GRO2LAM/archive/py3_compatibility.zip
unzip py3_compatibility.zip

printf "${LBlue} Collecting garbage ${Bcolor}\n\n"
rm py3_compatibility.zip
rm G2L_iBeta

cd GRO2LAM-py3_compatibility
python3 setup
printf "\n${Green} Install finished ${Bcolor}\n"
./run
